services:
  backend:
    build: "./backend"
    container_name: backend
    environment:
      DB_HOST: db
      DB_DATABASE: hackathon_reservas
      DB_USERNAME: admin
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
      - /app/backend/vendor
    depends_on:
      - db
    networks:
      - app

  frontend:
    build: "./frontend"
    container_name: frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    networks:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'hackathon_reservas'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - app
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - app

networks:
  app:
    driver: bridge